name: alliancestudent
favicon: null
layout_spectrum: 0.85663
typography_spectrum: 0.83776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0d4c4'
    - '#b4997c'
    - '#945d38'
    - '#200801'
    - '#54250a'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
